steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '$_REPO_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud',
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        '$_IMAGE',
        '--region',
        'asia-south1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - '$_IMAGE'
